name: Build and Deploy to ECS

on:
  push:
    brnaches:
       - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: devops-pro-app
  ECS_CLUSTER: devops-pro-cluster
  ECS_SERVICE: devops-pro-service
  CONTAINER_NAME: app
  TASK_DEFINITION_FAMILY: devops-pro-task

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      -name: Configure AWS credentials from GitHub OIDC
       uses: aws-actions/configure-aws-credentials@v4
       with:
         role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
         aws-region: ${{ env.AWS_REGION }}

      -name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2

      -name: Build, tag, and push image
       id: build-image
       env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         IMAGE_TAG: ${{ github.sha }}
       run: |
         aws ecs describe-task-definition \
           --task-definition $TASK_DEFINITION_FAMILY \
           --query taskDefinition > task-definition.json

       - name: Render new task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy task definition to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true    
       
